server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    location / {
        default_type text/plain;
        return 200 "LAB_SINKHOLE OK\n";
    }
    location /beacon {
        return 204;
    }
}
